spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: sales-analytics-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  datasource:
    url: jdbc:mysql://localhost:3306/ConnectEvent?useUnicode=true&characterEncoding=utf8mb4&collation=utf8mb4_unicode_ci


